

# http://htmlbook.ru/samhtml/tekst/spetssimvoly
# https://stackoverflow.com/questions/275174/how-do-i-perform-html-decoding-encoding-using-python-django
# https://coderoad.ru/5068951/Что-означают-lt-и-gt
def html_decode(s):
    """
    Returns the ASCII decoded version of the given HTML string. This does
    NOT remove normal HTML tags like <p>.
    """
    htmlCodes = (

            ('&#39;', "'"),
            ('&quot;', '"'),
            ('&gt;', '>'),
            ('&lt;', '<'),
            ('&amp;', '&'),
            ('<br />', ''),
            ('&nbsp;',' '),
            ('&copy;', '©'),
            ('&nbsp;', ' '),
            ('&pound;', '£'),
            ('&euro;', '€'),
            ('&para;', '¶'),
            ('&sect;', '§'),
            ('&copy;', '©'),
            ('&reg;', '®'),
            ('&trade;', '™'),
            ('&deg;', '°'),
            ('&plusmn;', '±'),
            ('&frac14;', '¼'),
            ('&frac12;', '½'),
            ('&frac34;', '¾'),
            ('&times;', '×'),
            ('&divide;', '÷'),
            ('&fnof;', 'ƒ'),
            ('&Alpha;', 'Α'),
            ('&Beta;', 'Β'),
            ('&Gamma;', 'Γ'),
            ('&Delta;', 'Δ'),
            ('&Epsilon;', 'Ε'),
            ('&Zeta;', 'Ζ'),
            ('&Eta;', 'Η'),
            ('&Theta;', 'Θ'),
            ('&Iota;', 'Ι'),
            ('&Kappa;', 'Κ'),
            ('&Lambda;', 'Λ'),
            ('&Mu;', 'Μ'),
            ('&Nu;', 'Ν'),
            ('&Xi;', 'Ξ'),
            ('&Omicron;', 'Ο'),
            ('&Pi;', 'Π'),
            ('&Rho;', 'Ρ'),
            ('&Sigma;', 'Σ'),
            ('&Tau;', 'Τ'),
            ('&Upsilon;', 'Υ'),
            ('&Phi;', 'Φ'),
            ('&Chi;', 'Χ'),
            ('&Psi;', 'Ψ'),
            ('&Omega;', 'Ω'),
            ('&alpha;', 'α'),
            ('&beta;', 'β'),
            ('&gamma;', 'γ'),
            ('&delta;', 'δ'),
            ('&epsilon;', 'ε'),
            ('&zeta;', 'ζ'),
            ('&eta;', 'η'),
            ('&theta;', 'θ'),
            ('&iota;', 'ι'),
            ('&kappa;', 'κ'),
            ('&lambda;', 'λ'),
            ('&mu;', 'μ'),
            ('&nu;', 'ν'),
            ('&xi;', 'ξ'),
            ('&omicron;', 'ο'),
            ('&pi;', 'π'),
            ('&rho;', 'ρ'),
            ('&sigmaf;', 'ς'),
            ('&sigma;', 'σ'),
            ('&tau;', 'τ'),
            ('&upsilon;', 'υ'),
            ('&phi;', 'φ'),
            ('&chi;', 'χ'),
            ('&psi;', 'ψ'),
            ('&omega;', 'ω'),
            ('&ndash;', '–'),
            ('&mdash;', '—'),
            ('&lsquo;', '‘'),
            ('&rsquo;', '’'),
            ('&sbquo;', '‚'),
            ('&ldquo;', '“'),
            ('&rdquo;', '”'),
            ('&bdquo;', '„'),
            ('&laquo;', '«'),
            ('&raquo;', '»'),
            ('&larr;', '←'),
            ('&uarr;', '↑'),
            ('&rarr;', '→'),
            ('&darr;', '↓'),
            ('&harr;', '↔'),
            ('&spades;', '♠'),
            ('&clubs;', '♣'),
            ('&hearts;', '♥'),
            ('&diams;', '♦'),
            ('&quot;', '"'),
            ('&amp;', '&'),
            ('&lt;', '<'),
            ('&gt;', '>'),
            ('&hellip;', '…'),
            ('&prime;', '′'),
            ('&Prime;', '″'),
            ('<p>', ""),
            ('</p>', "\n"),
        )
    for code in htmlCodes:
        s = s.replace(code[0], code[1])
    return s
